id: IA77E37A7
ocr_import_info:
  timestamp: '2023-08-17T01:57:40.312390+00:00'
  batch_id: batch-4c40
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-17 03:36:55.573905+00:00
last_modified: 2023-08-17 03:36:55.573911+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W20876
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW20876
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་བརྒྱུད་སྔགས་མཛོད།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9546013743834084
  ocr_word_median_confidence_index: 0.9975674
bases:
  I1539:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1539
      total_pages: 530
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1539.txt
    statistics:
      ocr_word_median_confidence_index: 0.9980808750000001
      ocr_word_mean_confidence_index: 0.9574258472886686
  I1540:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1540
      total_pages: 440
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1540.txt
    statistics:
      ocr_word_median_confidence_index: 0.9960212150000001
      ocr_word_mean_confidence_index: 0.9492138753563432
  I1538:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1538
      total_pages: 477
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1538.txt
    statistics:
      ocr_word_median_confidence_index: 0.99917678
      ocr_word_mean_confidence_index: 0.9656986910851566
  I1541:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1541
      total_pages: 439
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1541.txt
    statistics:
      ocr_word_median_confidence_index: 0.99616763
      ocr_word_mean_confidence_index: 0.9476814219499788
  I1535:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1535
      total_pages: 524
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1535.txt
    statistics:
      ocr_word_median_confidence_index: 0.99567604
      ocr_word_mean_confidence_index: 0.9474989168131791
  I1534:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1534
      total_pages: 503
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1534.txt
    statistics:
      ocr_word_median_confidence_index: 0.9983796
      ocr_word_mean_confidence_index: 0.9589656119761901
  I1537:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1537
      total_pages: 508
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1537.txt
    statistics:
      ocr_word_median_confidence_index: 0.9966537
      ocr_word_mean_confidence_index: 0.9508487291205298
  I1536:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1536
      total_pages: 597
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1536.txt
    statistics:
      ocr_word_median_confidence_index: 0.99767345
      ocr_word_mean_confidence_index: 0.9550883354687981
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
